server:
  port: 8090
spring:
  application:
    name: auth-service
  cloud:
    nacos:
      server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_demo?useSSL=false
    username: root
    password: 123456 # 替换
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

